# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='action',
            field=models.CharField(choices=[('building_up', 'upgrade')], max_length=50),
        ),
    ]
